export const credentials = {
  sauceDemoUrl: 'https://www.saucedemo.com/',
  sauceDemoTitle: 'Products',
  sauceCheckoutTitle: 'Checkout: Overview',
  sauceInventoryItems: [
    'Sauce Labs Backpack',
    'Sauce Labs Bike Light',
    'Sauce Labs Bolt T-Shirt',
    'Sauce Labs Fleece Jacket',
    'Sauce Labs Onesie',
    'Test.allTheThings() T-Shirt (Red)',
  ],
  sauceInventoryItemsPrices: [
    '$29.99',
    '$9.99',
    '$15.99',
    '$49.99',
    '$7.99',
    '$15.99',
  ],
  sauceFirstName: 'Zakir',
  sauceLastName: 'Kalayci',
  sauceZipCode: '12345',
  sauceCard: 'SauceCard #31337',
  sauceShippingInfo: 'Free Pony Express Delivery!',
  sauseTotalPrice: 'Total: $10.79',
  sauceCheckoutCompleteTitle: 'Thank you for your order!',
}
